version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: leonvincii
      POSTGRES_PASSWORD: lv93
      POSTGRES_DB: unichat_db
    # The port 8081 is where django application will interact with
    # /fmaps/settings.py for DATABASE configuration, the port is 8081
    ports:
      - 8081:5432

# System: PostgreSQL
# Server: db
# Username: leonvincii
# Password: lv93
# Database: unichat_db
  adminer:
    image: adminer
    ports:
        - 8080:8080